const __setType = (type) => {let f = ((...args) => Object.assign({type}, ...args)); f.type = type; return f;};

export const PROXIMITY_AIRPORT_NEAR_SUCCESS = __setType('proximity/AIRPORT_NEAR_SUCCESS');
export const PROXIMITY_LOAD_ALL_SUCCESS = __setType("proximity/LOAD_ALL_SUCCESS");

export const PROXIMITY_LOCATION_BY_ADDRESS_SUCCESS = __setType("proximity/LOCATION_BY_ADDRESS_SUCCESS");
export const PROXIMITY_LOCATION_DRIVE_DISTANCE_SUCCESS = __setType("proximity/LOCATION_DRIVE_DISTANCE_SUCCESS");

export const TOOLS_QPX_GOOGLE_SUCCESS = __setType("tools/QPX_GOOGLE_SUCCESS");
export const TOOLS_TRAFFIC_GOOGLE_SUCCESS = __setType("tools/TRAFFIC_GOOGLE_SUCCESS");
export const TOOLS_TRAFFIC_AVAILABLE_LIST_SUCCESS = __setType("tools/TRAFFIC_AVAILABLE_LIST_SUCCESS");

export const TOOLS_GTC_AIRPORT_LIST_SUCCESS = __setType('gtc/AIRPORT_LIST_SUCCESS');
export const TOOLS_GTC_HELICOPTER_LIST_SUCCESS = __setType('gtc/HELICOPTER_LIST_SUCCESS');
export const TOOLS_GTC_GET_QUERY_RESULTS_SUCCESS = __setType('gtc/GET_QUERY_RESULTS_SUCCESS');
export const TOOLS_GTC_GET_QUERY_HELICOPTER_RESULT_SUCCESS = __setType('gtc/GET_QUERY_HELICOPTER_RESULT_SUCCESS');

export const TOOLS_EVENT_VIEWER_GET_CATEGORIES_SUCCESS = __setType('eventViewer/GET_CATEGORIES_SUCCESS');
export const TOOLS_EVENT_VIEWER_GET_EVENTS_SUCCESS = __setType('eventViewer/GET_EVENTS_SUCCESS');

export const TOOLS_FWAT_GET_AIRCRAFT_ICAOS_SUCCESS = __setType('fwat/GET_AIRCRAFT_ICAOS_SUCCESS');
export const TOOLS_FWAT_GET_FLIGHTS_SUCCESS = __setType('fwat/GET_FLIGHTS_SUCCESS');
export const TOOLS_FWAT_GET_AIRCRAFT_CLASSES_AND_SAFETY_RATINGS = __setType('fwat/GET_AIRCRAFT_CLASSES_AND_SAFETY_RATINGS_SUCCESS');

export const TOOLS_FLIGHT_HISTORY_AIRPORTS_VALUES_SUCCESS = __setType('flightHistory/TOOLS_AIRPORTS_VALUES_SUCCESS');

export const TOOLS_EVENT_FLIGHT_PREDICTION_MATRIX_SUCCESS = __setType('efpm/EVENT_FLIGHT_PREDICTION_MATRIX_SUCCESS');


export const REDUX_LOADING_BAR = __setType("REDUX_LOADING_BAR");
